spring:
  datasource:
    username: root
    password: Myx521++
    url: jdbc:mysql://10.162.140.36:3306/fdu_postgraduate_score
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

    filters: stat
    initialization-mode: always
#    schema:
#      - classpath:sql/dep.sql
#      - classpath:sql/emp.sql
  jackson:
    property-naming-strategy: SNAKE_CASE
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mybatis/mapper/*
#  configuration:
#    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.jaryn.recorder.mapper.*: DEBUG

# 报考年份
fdu:
  postgraduate:
    year: 2024
    permitsPerSecond: 20